# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDS-iOS-APP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDS-iOS-APP
  pod 'ProjectOxfordFace', :path => '~/Documents/Cognitive-Face-iOS'

  target 'SDS-iOS-APPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  plugin 'cocoapods-keys', {
    :project => "SDS-iOS-APP",
    :keys => [
      "FACEAPIKEY",
      "FACEAPIURL"
    ]
  }

end
